import { Inter } from 'next/font/google'
import './globals.css'
import Topbar from '@/components/Topbar'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

import "boxicons/css/boxicons.min.css";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NepaUs News',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Topbar />
        <hr />
        <Navbar />
        <div className="max-w-[1300px] m-auto px-4">{children}</div>

        <Footer />
      </body>
    </html>
  )
}
